import type { YouTubeSourceVideo, ViralClip, ConnectedChannel, UserProfile, CaptionStyle } from '../types';

export const DEFAULT_CAPTION_STYLES: Record<string, CaptionStyle> = {
  tiktok: {
    preset: 'tiktok',
    fontFamily: 'Montserrat, sans-serif',
    fontSize: 32,
    position: 'bottom',
    offsetY: 75,
    activeWordColor: '#facc15',
    normalWordColor: '#ffffff',
    activeWordBackground: 'rgba(0, 0, 0, 0.85)',
    strokeColor: '#000000',
    textCase: 'uppercase',
    autoEmoji: true,
    shadowGlow: true,
    showCaptions: true
  },
  shorts: {
    preset: 'shorts',
    fontFamily: 'Bebas Neue, sans-serif',
    fontSize: 40,
    position: 'center',
    offsetY: 55,
    activeWordColor: '#06b6d4',
    normalWordColor: '#f3f4f6',
    strokeColor: '#0f172a',
    textCase: 'uppercase',
    autoEmoji: true,
    shadowGlow: true,
    showCaptions: true
  },
  reels: {
    preset: 'reels',
    fontFamily: 'Plus Jakarta Sans, sans-serif',
    fontSize: 28,
    position: 'bottom',
    offsetY: 80,
    activeWordColor: '#ec4899',
    normalWordColor: '#ffffff',
    backgroundColor: 'rgba(15, 23, 42, 0.8)',
    strokeColor: 'transparent',
    textCase: 'capitalize',
    autoEmoji: true,
    shadowGlow: false,
    showCaptions: true
  },
  karaoke: {
    preset: 'karaoke',
    fontFamily: 'Outfit, sans-serif',
    fontSize: 36,
    position: 'center',
    offsetY: 50,
    activeWordColor: '#a855f7',
    normalWordColor: 'rgba(255, 255, 255, 0.5)',
    strokeColor: '#000000',
    textCase: 'normal',
    autoEmoji: true,
    shadowGlow: true,
    showCaptions: true
  }
};

export const SAMPLE_YOUTUBE_VIDEOS: YouTubeSourceVideo[] = [
  {
    id: 'vid-1',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    title: 'How AI Agents Will Build million-dollar SaaS Companies in 2026',
    channelName: 'Tech Visionaries Podcast',
    durationSeconds: 2740,
    formattedDuration: '45:40',
    thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
    publishedAt: '2 days ago',
    videoPreviewUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    clipsGenerated: 6,
  },
  {
    id: 'vid-2',
    url: 'https://www.youtube.com/watch?v=3JZ_D3ELwOQ',
    title: 'Alex Hormozi: The Secret Mindset Behind $100M+ Businesses',
    channelName: 'Entrepreneur Mastermind',
    durationSeconds: 4200,
    formattedDuration: '1:10:00',
    thumbnailUrl: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800&auto=format&fit=crop&q=80',
    videoPreviewUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    publishedAt: '5 days ago',
    clipsGenerated: 8,
  },
  {
    id: 'vid-3',
    url: 'https://www.youtube.com/watch?v=L_LUpnjgPso',
    title: 'The Future of Robotics & Neural Interfaces - In-Depth Interview',
    channelName: 'Future Tech Daily',
    durationSeconds: 1890,
    formattedDuration: '31:30',
    thumbnailUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=80',
    videoPreviewUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    publishedAt: '1 week ago',
    clipsGenerated: 5,
  }
];

export const INITIAL_CLIPS: ViralClip[] = [
  {
    id: 'clip-101',
    videoId: 'vid-1',
    videoTitle: 'How AI Agents Will Build million-dollar SaaS Companies in 2026',
    title: '🔥 The 3 Secret Rules to 10X Your Productivity with AI (Don\'t Skip!)',
    description: 'Stop working 80 hours a week! Here is how elite founders leverage autonomous AI agents to scale. #AI #SaaS #Productivity #Shorts\n\n📌 Key Chapters:\n0:00 - High Retention Hook\n0:05 - The #1 AI Automation Framework\n0:20 - Actionable Takeaway\n\nSubscribe for daily masterclasses! #YouTubeShorts #Viral',
    hashtags: ['#AISaaS', '#Shorts', '#Viral', '#Entrepreneur', '#Tech'],
    tags: ['ai', 'saas', 'automation', 'business', 'shorts', 'youtube shorts', 'productivity', 'entrepreneur'],
    viralityScore: 99,
    viralityReason: 'High emotional intrigue hook in first 2 seconds + strong call to action',
    startTime: 142,
    endTime: 172,
    duration: 30,
    aspectRatio: '9:16',
    faceTrackingMode: 'auto',
    captionStyle: DEFAULT_CAPTION_STYLES.tiktok,
    showCaptions: true,
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    removeSilence: true,
    autoZoom: true,
    status: 'draft',
    categoryId: '28',
    categoryName: 'Science & Technology',
    madeForKids: false,
    visibility: 'public',
    seoScore: 98,
    predictedCtr: '14.8%',
    transcript: [
      { id: 'w1', word: 'IF', start: 0.1, end: 0.3, emoji: '⚡' },
      { id: 'w2', word: 'YOU', start: 0.3, end: 0.5 },
      { id: 'w3', word: 'ARE', start: 0.5, end: 0.7 },
      { id: 'w4', word: 'STILL', start: 0.7, end: 0.9 },
      { id: 'w5', word: 'BUILDING', start: 0.9, end: 1.3, isKeyword: true },
      { id: 'w6', word: 'SOFTWARE', start: 1.3, end: 1.7 },
      { id: 'w7', word: 'THE', start: 1.7, end: 1.9 },
      { id: 'w8', word: 'OLD', start: 1.9, end: 2.2 },
      { id: 'w9', word: 'WAY,', start: 2.2, end: 2.5, emoji: '❌' },
      { id: 'w10', word: 'YOU', start: 2.6, end: 2.8 },
      { id: 'w11', word: 'ARE', start: 2.8, end: 3.0 },
      { id: 'w12', word: 'ALREADY', start: 3.0, end: 3.3 },
      { id: 'w13', word: 'BEHIND!', start: 3.3, end: 3.8, isKeyword: true, emoji: '🚀' },
      { id: 'w14', word: 'THE', start: 4.0, end: 4.2 },
      { id: 'w15', word: 'TOP', start: 4.2, end: 4.5 },
      { id: 'w16', word: '1%', start: 4.5, end: 4.8, emoji: '👑' },
      { id: 'w17', word: 'ENTREPRENEURS', start: 4.8, end: 5.4, isKeyword: true },
      { id: 'w18', word: 'ARE', start: 5.4, end: 5.6 },
      { id: 'w19', word: 'DEPLOYING', start: 5.6, end: 6.0 },
      { id: 'w20', word: 'AUTONOMOUS', start: 6.0, end: 6.5 },
      { id: 'w21', word: 'AGENTS', start: 6.5, end: 7.0, isKeyword: true, emoji: '🤖' },
      { id: 'w22', word: 'THAT', start: 7.1, end: 7.3 },
      { id: 'w23', word: 'WRITE', start: 7.3, end: 7.6 },
      { id: 'w24', word: 'CODE,', start: 7.6, end: 7.9 },
      { id: 'w25', word: 'TEST,', start: 7.9, end: 8.2 },
      { id: 'w26', word: 'AND', start: 8.2, end: 8.4 },
      { id: 'w27', word: 'DEPLOY', start: 8.4, end: 8.8 },
      { id: 'w28', word: 'IN', start: 8.8, end: 9.0 },
      { id: 'w29', word: 'MINUTES.', start: 9.0, end: 9.5, emoji: '⏱️' }
    ]
  },
  {
    id: 'clip-102',
    videoId: 'vid-1',
    videoTitle: 'How AI Agents Will Build million-dollar SaaS Companies in 2026',
    title: '🧠 Why 90% of Startups Fail (And How to Avoid It)',
    description: 'Discover the single biggest mistake founders make when validating business ideas. #StartupTips #Business #Success\n\n#Shorts #YouTubeShorts #Mindset',
    hashtags: ['#Startups', '#Mindset', '#Shorts', '#BusinessGrowth'],
    tags: ['startup', 'business', 'failure', 'advice', 'youtube shorts'],
    viralityScore: 94,
    viralityReason: 'Contrarian statement + psychological curiosity gap',
    startTime: 410,
    endTime: 440,
    duration: 30,
    aspectRatio: '9:16',
    faceTrackingMode: 'center',
    captionStyle: DEFAULT_CAPTION_STYLES.shorts,
    showCaptions: true,
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=600&auto=format&fit=crop&q=80',
    removeSilence: true,
    autoZoom: false,
    status: 'draft',
    categoryId: '27',
    categoryName: 'Education',
    madeForKids: false,
    visibility: 'public',
    seoScore: 95,
    predictedCtr: '12.4%',
    transcript: [
      { id: 'w30', word: 'MOST', start: 0.1, end: 0.3 },
      { id: 'w31', word: 'PEOPLE', start: 0.3, end: 0.6 },
      { id: 'w32', word: 'FAIL', start: 0.6, end: 0.9, emoji: '💔', isKeyword: true },
      { id: 'w33', word: 'BECAUSE', start: 0.9, end: 1.2 },
      { id: 'w34', word: 'THEY', start: 1.2, end: 1.4 },
      { id: 'w35', word: 'FALL', start: 1.4, end: 1.6 },
      { id: 'w36', word: 'IN', start: 1.6, end: 1.8 },
      { id: 'w37', word: 'LOVE', start: 1.8, end: 2.1, emoji: '❤️' },
      { id: 'w38', word: 'WITH', start: 2.1, end: 2.3 },
      { id: 'w39', word: 'THEIR', start: 2.3, end: 2.5 },
      { id: 'w40', word: 'PRODUCT,', start: 2.5, end: 3.0 },
      { id: 'w41', word: 'NOT', start: 3.1, end: 3.3 },
      { id: 'w42', word: 'THE', start: 3.3, end: 3.5 },
      { id: 'w43', word: 'CUSTOMER\'S', start: 3.5, end: 4.0, isKeyword: true },
      { id: 'w44', word: 'PROBLEM!', start: 4.0, end: 4.6, emoji: '🎯' }
    ]
  },
  {
    id: 'clip-103',
    videoId: 'vid-2',
    videoTitle: 'Alex Hormozi: The Secret Mindset Behind $100M+ Businesses',
    title: '⚡ Alex Hormozi on the #1 Skill You Need in 2026',
    description: 'If you master this one skill, you will never go broke again. #Hormozi #Sales #Advice',
    hashtags: ['#AlexHormozi', '#Wealth', '#Skillset', '#ViralShorts'],
    tags: ['sales', 'hormozi', 'money', 'wealth'],
    viralityScore: 97,
    viralityReason: 'High authority speaker + urgency call-out',
    startTime: 820,
    endTime: 865,
    duration: 45,
    aspectRatio: '9:16',
    faceTrackingMode: 'split',
    captionStyle: DEFAULT_CAPTION_STYLES.reels,
    showCaptions: true,
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&auto=format&fit=crop&q=80',
    removeSilence: true,
    autoZoom: true,
    status: 'scheduled',
    scheduledDate: 'Tomorrow at 6:00 PM',
    publishedPlatforms: ['youtube', 'instagram'],
    categoryId: '27',
    categoryName: 'Education',
    madeForKids: false,
    visibility: 'public',
    seoScore: 97,
    predictedCtr: '15.2%',
    transcript: [
      { id: 'w45', word: 'THE', start: 0.1, end: 0.3 },
      { id: 'w46', word: 'ONLY', start: 0.3, end: 0.5 },
      { id: 'w47', word: 'THING', start: 0.5, end: 0.8 },
      { id: 'w48', word: 'STANDING', start: 0.8, end: 1.2 },
      { id: 'w49', word: 'BETWEEN', start: 1.2, end: 1.5 },
      { id: 'w50', word: 'YOU', start: 1.5, end: 1.7 },
      { id: 'w51', word: 'AND', start: 1.7, end: 1.9 },
      { id: 'w52', word: 'FINANCIAL', start: 1.9, end: 2.3 },
      { id: 'w53', word: 'FREEDOM', start: 2.3, end: 2.8, emoji: '💰', isKeyword: true },
      { id: 'w54', word: 'IS', start: 2.9, end: 3.1 },
      { id: 'w55', word: 'OFFER', start: 3.1, end: 3.4 },
      { id: 'w56', word: 'CREATION.', start: 3.4, end: 3.9, emoji: '💎' }
    ]
  }
];

export const CONNECTED_CHANNELS: ConnectedChannel[] = [
  {
    id: 'chan-yt',
    platform: 'youtube',
    name: 'Tech & Growth Shorts Channel',
    handle: '@TechGrowthShorts',
    avatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    subscribers: '142.5K Subscribers',
    connected: true,
    lastSync: 'Active (youtube.upload API)',
    channelId: 'UC_x5XG1OV2P6uZZ5FSM9Ttw',
    oauthScopes: ['https://www.googleapis.com/auth/youtube.upload', 'https://www.googleapis.com/auth/youtube.readonly'],
    autoPostingEnabled: false,
    defaultVisibility: 'public',
    defaultCategoryId: '28'
  },
  {
    id: 'chan-ig',
    platform: 'instagram',
    name: 'Daily Mindset Reels',
    handle: '@dailymindset.reels',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    subscribers: '215.8K Followers',
    connected: true,
    lastSync: 'Active (instagram.publish API)',
    oauthScopes: ['instagram_content_publish', 'pages_show_list'],
    autoPostingEnabled: false
  }
];

export const CURRENT_USER: UserProfile = {
  id: 'usr-99',
  name: 'Alex Rivera',
  email: 'alex.rivera@saasbuilder.io',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
  isLoggedIn: true
};
